export const text = {
    WEIGHT: "Weight",
    REPS: "Reps",
    SETS: "Sets",
    WEIGHTABR: "W",
    REPSABR: "R",
    SETSABR: "S",
    EXERCISES: "Exercises",
    NAME: "Name",
    EXERCISE: "Exercise",
    WORKOUT_DAY: "Workout Day",
    WORKOUT: "Workout",
    WORKOUTS: "Workouts",
    WORKOUT_DAYS: "Workout Days",
    SUBMIT: "Submit",
    NEXT: "Next",
    ADD_DAYS: "Add Days",
    ADD_DAY: "Add Day",
    ADD: "ADD",
    BACK: "Back",
    DAYS: "Days",
    CLOSE: "Close",
    EXIT: "Exit",
    CLEAR: "Clear",
    REST_DAY: "Rest Day",
    CALENDAR: "Calendar",
    ADD_EXERCISES: "Add Exercises",
    ADD_WORKOUT_DAYS: "Add Workout Days",
    ADD_WORKOUTS: "Add Workouts",
    SELECT_ACTIVE_WORKOUT: "Select Active Workout"
}